import React, { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate, useLocation } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { Button } from '../UI/Button';
import { Card } from '../UI/Card';
import './Auth.css';

export const Register = () => {
  const [formData, setFormData] = useState({
    email: '',
    password: '',
    confirmPassword: ''
  });
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const { register } = useAuth();
  const { t } = useTranslation();
  const navigate = useNavigate();
  const location = useLocation();

  useEffect(() => {
    // Check for error in URL params
    const params = new URLSearchParams(location.search);
    const error = params.get('error');
    if (error === 'auth_failed' || error === 'google_auth_failed') {
      alert('Authentication failed. Please try again.');
    }
  }, [location]);

  const validateForm = () => {
    const { email, password, confirmPassword } = formData;

    // Email checks
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      return 'Invalid email format';
    }

    // Password checks
    if (password.length < 6) {
      return 'Password must be at least 6 characters';
    }

    // Confirm password
    if (password !== confirmPassword) {
      return 'Passwords do not match';
    }

    return null; // no errors
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');

    const validationError = validateForm();
    if (validationError) {
      setError(validationError);
      return;
    }

    setLoading(true);

    try {
      await register({
        email: formData.email.trim().toLowerCase(),
        password: formData.password
      });
      navigate('/predictions');
    } catch (err) {
      setError(err.response?.data?.error || 'Registration failed');
    } finally {
      setLoading(false);
    }
  };

  const handleGoogleLogin = () => {
    // Redirect to backend Google OAuth
    window.location.href = `${import.meta.env.VITE_API_URL || 'http://localhost:3000'}/users/auth/google`;
  };

  return (
    <div className="auth-container">
      <Card className="auth-card">
        <div className="auth-header">
          <h1>{t("register.createAccount")}</h1>
          <p>{t("register.subtitle")}</p>
        </div>

        <form onSubmit={handleSubmit} className="auth-form">
          {error && <div className="error-message">{error}</div>}

          <div className="form-group">
            <label htmlFor="email">{t("email")}</label>
            <input
              id="email"
              type="email"
              value={formData.email}
              onChange={(e) => setFormData({ ...formData, email: e.target.value })}
              placeholder="your@email.com"
              required
              autoFocus
            />
          </div>

          <div className="form-group">
            <label htmlFor="password">{t("password")}</label>
            <input
              id="password"
              type="password"
              value={formData.password}
              onChange={(e) => setFormData({ ...formData, password: e.target.value })}
              placeholder="Enter password (min 6 characters)"
              required
            />
          </div>

          <div className="form-group">
            <label htmlFor="confirmPassword">{t("password.confirm")}</label>
            <input
              id="confirmPassword"
              type="password"
              value={formData.confirmPassword}
              onChange={(e) => setFormData({ ...formData, confirmPassword: e.target.value })}
              placeholder="Confirm your password"
              required
            />
          </div>

          <div className="username-notice">
            <span className="info-icon">ℹ️</span>
            <span>{t("register.usernameAutoGenerated")}</span>
          </div>

          <Button type="submit" loading={loading} size="large" fullwidth="true">
            {t("register.createAccount")}
          </Button>

          <p className="auth-link">
            {t("register.existingAccount")} <Link to="/login">{t("register.loginHere")}</Link>
          </p>
        </form>

        <div className="auth-divider">
          <span>{t("or")}</span>
        </div>

        <Button 
          onClick={handleGoogleLogin}
          variant="outline"
          size="large"
          fullwidth="true"
          className="google-btn"
        >
          <img src="https://www.google.com/favicon.ico" alt="Google" className="google-icon" />
          {t("Continue with Google")}
        </Button>
      </Card>
    </div>
  );
};
